application:
  name: dependency tree usage example
  screen:
    x: 0
    y: 0
    w: 1920
    h: 1080
    fps: 20
    screenMode: 1
    clearColor:
      r: 0
      g: 0
      b: 0
      a: 1
entities:
  - id: "0xdddddd"
    components:
      - type: position
        fields:
          x: 500
          y: 500
      - type: size
        fields:
          w: 100
          h: 100
      - type: sprite
        fields:
          path: "../assets/blitz.png"
    children:
      - id: "0xffffff"
        components:
          - type: position
            fields:
              x: 50
              y: 50
          - type: size
            fields:
              w: 10
              h: 10
          - type: sprite
            fields:
              path: "../assets/blitz.png"
